if(NOT "CONFIG" IN_LIST ARGS AND NOT "NO_MODULE" IN_LIST ARGS)
    list(GET ARGS 0 z_pkg_name)
    if(z_pkg_name STREQUAL "Protobuf" AND NOT "MODULE" IN_LIST ARGS)
        list(APPEND ARGS CONFIG)
    elseif("@VCPKG_LIBRARY_LINKAGE@" STREQUAL "static")
        set(Protobuf_USE_STATIC_LIBS ON)
    else()
        set(Protobuf_USE_STATIC_LIBS OFF)
    endif()
    unset(z_pkg_name)
endif()

find_program(Protobuf_PROTOC_EXECUTABLE NAMES protoc PATHS "${CMAKE_CURRENT_LIST_DIR}/../../../@HOST_TRIPLET@/tools/protobuf" NO_DEFAULT_PATH)

_find_package(${ARGS})
