if(CMAKE_VERSION VERSION_LESS 3.7)
    find_library(BZIP2_LIBRARY_DEBUG NAMES bz2d PATHS "${_VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}/debug/lib" NO_DEFAULT_PATH)
endif()
_find_package(${ARGS})
